version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_main
    ports:
      - "3000:3000" # Cambia el puerto según tu aplicación
    env_file:
      - .env